
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__dbus_hello_adaptor_h__ADAPTOR_MARSHAL_H
#define __dbusxx__dbus_hello_adaptor_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace com {
namespace example {

class hello_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    hello_adaptor()
    : ::DBus::InterfaceAdaptor("com.example.hello")
    {
        register_method(hello_adaptor, SayHello, _SayHello_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument SayHello_args[] = 
        {
            { "greeting", "s", true },
            { "response", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod hello_adaptor_methods[] = 
        {
            { "SayHello", SayHello_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod hello_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty hello_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface hello_adaptor_interface = 
        {
            "com.example.hello",
            hello_adaptor_methods,
            hello_adaptor_signals,
            hello_adaptor_properties
        };
        return &hello_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::string SayHello(const std::string& greeting) = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _SayHello_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::string argin1; ri >> argin1;
        std::string argout1 = SayHello(argin1);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} } 
#endif //__dbusxx__dbus_hello_adaptor_h__ADAPTOR_MARSHAL_H
